spring:
  application:
    name: Client
  datasource:
    url: jdbc:postgresql://localhost:5436/clientdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

t1:
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    topic:
      client_products: client_products
      client_credit_products: client_credit_products
      client_cards: client_cards

server:
  port: 8081
